Estudo_new/C#-AspNetCore/Formularios/Formularios/Models/ErrorViewModel.cs
using System;

namespace Formularios.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Models/Filme.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Formularios.Models
{
    /// <summary>
    /// Documentação annotations
    /// https://docs.microsoft.com/pt-br/dotnet/api/system.componentmodel.dataannotations?view=netcore-3.1
    /// </summary>
    public class Filme
    {

     
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "O {0} precisa ter entre {2} e {1} caracteres...")]
        public string Titulo { get; set; }



        [DataType(DataType.DateTime, ErrorMessage = "Data em formato inválido")]
        [Required(ErrorMessage = "O campo {0} é obrigátorio")]
        [Display(Name = "Data de Lançamento")]
        public DateTime DataLancamento { get; set; }



        [RegularExpression(@"^[A-Z]+[a-zA-Z\u00C0-\u00FF""'\w-]*$", ErrorMessage = "Formato de Gênero invalido")]//, ErrorMessage ="Formato inválido.")]
        [StringLength(30, ErrorMessage = "Maximo de {1} caracteres"),Required(ErrorMessage ="O campo {0} é obrigátorio")]//forma de sobrecarga de annotations
       [DisplayName("Gênero")]
        public string Genero { get; set; }

        [Range(1, 1000)]
        [Required(ErrorMessage = "Campo {0} obrigátorioo")]
        [Column(TypeName = "decimal(18,2")]//annotations para valor de campo no banco
        public decimal Valor { get; set; }


        [RegularExpression(@"^[0-5]*$", ErrorMessage ="Numeros somente de 1 a 5.")]
        [DisplayName("Avaliação")]
        [Required(ErrorMessage = "Preencha o campo avaliação")]
        public int Avaliacao { get; set; }
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Controllers/FilmeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Formularios.Models;
using Microsoft.AspNetCore.Mvc;

namespace Formularios.Controllers
{
    public class FilmeController : Controller
    {
        [HttpGet]
        public IActionResult Adicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(Filme filme)
        {
            if (ModelState.IsValid)
            {
                //alguma coisa
            }
            return View(filme);
        }
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Controllers/Filmes_ScaffoldController.cs
using Formularios.Data;
using Formularios.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Formularios.Controllers
{
    public class Filmes_ScaffoldController : Controller
    {
        private readonly FormulariosContext _context;

        public Filmes_ScaffoldController(FormulariosContext context)
        {
            _context = context;
        }

        // GET: Filmes_Scaffold
        public async Task<IActionResult> Index()
        {
            return View(await _context.Filme.ToListAsync());
        }

        // GET: Filmes_Scaffold/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filmes_Scaffold/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,DataLancamento,Genero,Valor,Avaliacao")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filmes_Scaffold/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            return View(filme);
        }

        // POST: Filmes_Scaffold/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,DataLancamento,Genero,Valor,Avaliacao")] Filme filme)
        {
            if (id != filme.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filmes_Scaffold/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.Id == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // POST: Filmes_Scaffold/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filme.FindAsync(id);
            _context.Filme.Remove(filme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filme.Any(e => e.Id == id);
        }
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Formularios.Models;

namespace Formularios.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Views/Filme/Adicionar.cshtml
@model Formularios.Models.Filme 


@{
    ViewData["Title"] = "Adicionar Filme";
}

    <h4>@ViewData["Title"]</h4>

<div class="row">
    <div class="col-md-9">
        <form asp-action="Adicionar">
            @*<div class="form-row">
                <div class="form-group col-md-4">
                    <label for="inputEmail4">Email</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="Email">
                </div>
                <div class="form-group col-md-4">
                    <label for="inputPassword4">Senha</label>
                    <input type="password" class="form-control" id="inputPassword4" placeholder="Senha"> teste coluna de 3 itens
                </div>
                <div class="form-group col-md-4">
                    <label for="inputPassword4">Confirmação Senha</label>
                    <input type="password" class="form-control" id="inputPassword4" placeholder="Confirmação senha">
                </div>
            </div>*@

            <!--All - para todos os erros encontrados-->
            <!--ModelOnly - vai mostrar todos os erros referente a model-->
            <!--None - Nao mostra nenhum erro encontrado-->

            <div class="text-danger" asp-validation-summary="ModelOnly">

            </div>

            <hr />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataLancamento" class="control-label"></label>
                <input asp-for="DataLancamento" class="form-control" />
                <span asp-validation-for="DataLancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Valor" class="control-label"></label>
                <input asp-for="Valor" class="form-control" />
                <span asp-validation-for="Valor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Avaliacao" class="control-label"></label>
                <input asp-for="Avaliacao" class="form-control" />
                <span asp-validation-for="Avaliacao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Adicionar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<!--é necessario adicionar os scripts abaixo para validar na view sem fazer a chamada pro servidor-->
@section Scripts{ 
    @{ 
        await Html.RenderPartialAsync("_ValidationScriptsPartial.cshtml");
    }
}

Estudo_new/C#-AspNetCore/Formularios/Formularios/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Formularios</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Formularios</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filme" asp-action="Adicionar">Filmes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Filmes_Scaffold" asp-action="Create">Filmes Scafold</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Formularios - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>